### PR TITLE
Fix early termination of daemon mode

### PR DESCRIPTION
**Pull request by joke**
Replaced docker event log file with pipe to block read loop.

### CODE REVIEW

**Comment by joke** [comment]
The event loop terminates early because the while loop does not block on normal files.
As a result of this the daemon mode is not working.

**Comment by dreamcat4** [comment]
Thank you for submitting this Pull Request. As expressed in git commit history, the `while read` loop of daemon mode has had problems. But now in latest `v1.09` of this pipework image **_we really hope it's fixed**_.

I understand your modification however it does not seem to matter. And unfortunately for FIFO (unix socket) they have other unknown hanging issue(s) which can be read about here:

https://github.com/docker/docker/issues/12023

So I am keen to avoid going back to FIFO after such previous problems.

@joke ok you say: 

> The event loop terminates early because the while loop does not block on normal files. As a result of this the daemon mode is not working.

But did you really experience that on your local machine?

For me it does not happen with the latest `v1.0.9` image. Maybe it didn't work for you because either a) was old image (version 1.0.5-1.0.8 = not working damen mode). Or perhaps b) some other reason we don't know yet? I am happy to investigate.

In respect to your PR code change here: it should not be needed. In recent `v1.0.9` we changed it to **_new**_ loop code:

https://github.com/dreamcat4/docker-images/blob/pipework-1.0.9/pipework/entrypoint.sh#L418-419

Which is same as saying:

``` sh
tail -f $docker_events_log | while true; do
  read eventline
  # process line
done
```

Since it works (for me) I am wondering what else can cause your pipework daemon to die? Some possibilities:
- Please regard that the setting `pipework_wait` will cause daemon mode to die after N seconds. That is by design.
- You can set ENV var `debug=true` to get full trace log of what pipework container is doing. Then if it dies then please gist the output `docker logs pipework` command.

Real working example:

My own orchestration settings in `crane.yml` file:

``` yaml
containers:
  pipework:
    image: dreamcat4/pipework
    dockerfile: pipework
    run:
      restart: always
      volume:
        - /var/run/docker.sock:/docker.sock
      privileged: true
      pid: host
      net: host
      env:
        - run_mode=batch,daemon
        - debug=true
```

It should be similar for `docker-compose`. This pipework image requires version `1.3.0` of Compose.

Hope that helps! :)

**Comment by joke** [comment]
Sorry. You are right. It's working now. 

I was stuck with an old version of container now and did realize it.

Sorry for the inconvenience.

**Comment by dreamcat4** [comment]
Ok great! Thank you for the feedback.

I appreciate the feedback. It is good to know that the public build of the image is working for other people. I only have my developer machine to test things on. Which is only 1 configuration (ubuntu docker host).

Looking forward to getting it working on CoreOS too now. And try my best to solve any remaining problems. Don't hestitate to raise further issues if you see anything else.

**Pull request closed without merging**
